{
  "hash": "bc75da82eda14d8259f378e37e84ecf2",
  "result": {
    "engine": "jupyter",
    "markdown": "# Workplace interaction\n\n::: {#cell-1 .cell execution_count=1}\n``` {.python .cell-code}\n%load_ext autoreload\n%autoreload 2\n```\n:::\n\n\nImport some plotting libraries and set some defaults:\n\n::: {#cell-3 .cell execution_count=2}\n``` {.python .cell-code}\nimport sys\nimport numpy as np\nimport pandas as pd\nfrom IPython.display import display, Markdown\nimport matplotlib.pyplot as plt\nimport seaborn as sns\nsns.set()\nsns.set_style(\"whitegrid\")\n\nimport random\nrandom_seed = 5\n\nsys.path.append('..')\nfrom global_params import load_params\n```\n:::\n\n\n> **Tip:**  \n> Producing figures in svg format (scalable vector graphics) makes for sharp plots on webpages. However, if you make plots with thousands of observations you should set this to `'png'` instead:\n\n::: {#cell-5 .cell execution_count=3}\n``` {.python .cell-code}\n%config InlineBackend.figure_formats = ['svg'] \n```\n:::\n\n\n> **Tip:**  \n> Some values apply globally to your analysis. E.g., sample sizes, cutoffs, names, rates, etc. Keeping those in a a yml file like `interaction_params.yml` and loading them in each notebook avoids the risk of manually adding/updating them in each notebook where they are used. You can use the `load_globals` function imported above from `global_params.py` to produce an object holding all the global values:\n\n::: {#cell-7 .cell execution_count=4}\n``` {.python .cell-code}\nparams = load_params('../global_params.yml')\nparams\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\n{'questions': ['I enjoy working with bioinformatics',\n               'I feel confident using the cluster',\n               'I understand reproducible research'],\n 'sample_size': 24}\n```\n:::\n:::\n\n\n::: {#cell-8 .cell execution_count=5}\n``` {.python .cell-code}\nparams.sample_size\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n24\n```\n:::\n:::\n\n\n## Sampling\n\n::: {#cell-10 .cell execution_count=6}\n``` {.python .cell-code}\nsubjects = pd.read_csv('../data/data_table.csv')\nassert subjects.index.size == params.sample_size\n```\n:::\n\n\n> **Tip:**  \n> By adding a label and caption to a cell displaying a table, you can refer to that table elsewhere and insert it in a manuscript.\n\n::: {#tbl-subjects .cell tbl-cap='People included in the analysis.' execution_count=7}\n``` {.python .cell-code}\nsubjects\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>name</th>\n      <th>age</th>\n      <th>sex</th>\n      <th>position</th>\n      <th>nationality</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Julie</td>\n      <td>27</td>\n      <td>F</td>\n      <td>PhDstudent</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Thomas</td>\n      <td>33</td>\n      <td>M</td>\n      <td>Postdoc</td>\n      <td>GB</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Emilie</td>\n      <td>23</td>\n      <td>F</td>\n      <td>PhDstudent</td>\n      <td>CH</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Sofie</td>\n      <td>31</td>\n      <td>F</td>\n      <td>Postdoc</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Sara</td>\n      <td>29</td>\n      <td>F</td>\n      <td>Postdoc</td>\n      <td>US</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Cecilie</td>\n      <td>34</td>\n      <td>F</td>\n      <td>Postdoc</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Anders</td>\n      <td>32</td>\n      <td>M</td>\n      <td>PhDstudent</td>\n      <td>UK</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Emma</td>\n      <td>42</td>\n      <td>F</td>\n      <td>Professor</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Caroline</td>\n      <td>31</td>\n      <td>F</td>\n      <td>PhDstudent</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Laura</td>\n      <td>30</td>\n      <td>F</td>\n      <td>Postdoc</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Mikkel</td>\n      <td>33</td>\n      <td>M</td>\n      <td>Postdoc</td>\n      <td>NL</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Jens</td>\n      <td>27</td>\n      <td>M</td>\n      <td>PhDstudent</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Andreas</td>\n      <td>29</td>\n      <td>M</td>\n      <td>PhDstudent</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Jakob</td>\n      <td>28</td>\n      <td>M</td>\n      <td>PhDstudent</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Mathilde</td>\n      <td>61</td>\n      <td>F</td>\n      <td>Professor</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>Katrine</td>\n      <td>35</td>\n      <td>F</td>\n      <td>Postdoc</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>Poul</td>\n      <td>30</td>\n      <td>M</td>\n      <td>Postdoc</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>Anna</td>\n      <td>26</td>\n      <td>F</td>\n      <td>PhDstudent</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>Peter</td>\n      <td>42</td>\n      <td>M</td>\n      <td>Professor</td>\n      <td>GB</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>Ida</td>\n      <td>53</td>\n      <td>F</td>\n      <td>Postdoc</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>Freja</td>\n      <td>30</td>\n      <td>F</td>\n      <td>Postdoc</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>Maria</td>\n      <td>39</td>\n      <td>F</td>\n      <td>Professor</td>\n      <td>UK</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>Amalie</td>\n      <td>29</td>\n      <td>F</td>\n      <td>PhDstudent</td>\n      <td>DK</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>Camilla</td>\n      <td>35</td>\n      <td>F</td>\n      <td>Postdoc</td>\n      <td>DK</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n> **Tip:**  \n> By generaing markdown for descriptions that will eventually end up in the manuscript, you can imbed python values. It also ensures that the manuscript exactly reflects the notebook.\n\n::: {#cell-doc-sampling .cell execution_count=8}\n\n::: {#doc-sampling .cell-output .cell-output-display .cell-output-markdown execution_count=8}\n\n\nThe 24 subjects from workplaces in Denmark were interviewed .... blah blah \nblah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah \nblah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah \n\n:::\n:::\n\n\n## Interviews\n\n::: {#cell-doc-interviews .cell execution_count=9}\n\n::: {#doc-interviews .cell-output .cell-output-display .cell-output-markdown execution_count=9}\n\n\nThe 24 subjects were asked to score the follow statements:\n\n1. I enjoy working with bioinformatics\n2. I feel confident using the cluster\n3. I understand reproducible research\n\n\n:::\n:::\n\n\nIn interviewed 24 workplace individuals were interviewed by .... blah, blah, blah, blah, blah, blah, blah, blah, blah, blah, blah, blah, blah, blah, \nblah, blah, blah, blah, blah, blah, blah, blah, blah, blah, blah, blah, blah, blah, \n\n::: {#cell-18 .cell execution_count=10}\n``` {.python .cell-code}\n\n#| label: tbl-measured-informality\n#| tbl-cap: \"Informality quantified for subjects in the study.\"\n\ndf = pd.DataFrame({'name': subjects.name, \n                   'seniority': np.random.randint(0, 5, params.sample_size), \n                   'age': subjects.age})\ndf['informality'] = np.random.normal(loc=10, scale=1, size=params.sample_size)\ndf\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>name</th>\n      <th>seniority</th>\n      <th>age</th>\n      <th>informality</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>Julie</td>\n      <td>1</td>\n      <td>27</td>\n      <td>7.486977</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Thomas</td>\n      <td>0</td>\n      <td>33</td>\n      <td>11.184059</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Emilie</td>\n      <td>1</td>\n      <td>23</td>\n      <td>10.591383</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>Sofie</td>\n      <td>4</td>\n      <td>31</td>\n      <td>10.834241</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>Sara</td>\n      <td>3</td>\n      <td>29</td>\n      <td>9.534070</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>Cecilie</td>\n      <td>3</td>\n      <td>34</td>\n      <td>10.061407</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>Anders</td>\n      <td>3</td>\n      <td>32</td>\n      <td>9.993442</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>Emma</td>\n      <td>0</td>\n      <td>42</td>\n      <td>9.799740</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>Caroline</td>\n      <td>1</td>\n      <td>31</td>\n      <td>7.892410</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>Laura</td>\n      <td>3</td>\n      <td>30</td>\n      <td>11.185854</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>Mikkel</td>\n      <td>1</td>\n      <td>33</td>\n      <td>9.087897</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>Jens</td>\n      <td>1</td>\n      <td>27</td>\n      <td>8.331392</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>Andreas</td>\n      <td>2</td>\n      <td>29</td>\n      <td>9.746443</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>Jakob</td>\n      <td>3</td>\n      <td>28</td>\n      <td>9.409442</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>Mathilde</td>\n      <td>4</td>\n      <td>61</td>\n      <td>11.605031</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>Katrine</td>\n      <td>0</td>\n      <td>35</td>\n      <td>8.961985</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>Poul</td>\n      <td>4</td>\n      <td>30</td>\n      <td>8.616172</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>Anna</td>\n      <td>2</td>\n      <td>26</td>\n      <td>9.719866</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>Peter</td>\n      <td>0</td>\n      <td>42</td>\n      <td>9.236514</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>Ida</td>\n      <td>1</td>\n      <td>53</td>\n      <td>11.098911</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>Freja</td>\n      <td>1</td>\n      <td>30</td>\n      <td>9.701213</td>\n    </tr>\n    <tr>\n      <th>21</th>\n      <td>Maria</td>\n      <td>1</td>\n      <td>39</td>\n      <td>10.647020</td>\n    </tr>\n    <tr>\n      <th>22</th>\n      <td>Amalie</td>\n      <td>0</td>\n      <td>29</td>\n      <td>10.984688</td>\n    </tr>\n    <tr>\n      <th>23</th>\n      <td>Camilla</td>\n      <td>2</td>\n      <td>35</td>\n      <td>12.089424</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#tbl-mean-informality .cell tbl-cap='Mean interaction scores by seniority and age' execution_count=11}\n``` {.python .cell-code}\ndf.groupby(['seniority']).mean(numeric_only=True).reset_index()\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>seniority</th>\n      <th>age</th>\n      <th>informality</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0</td>\n      <td>36.200000</td>\n      <td>10.033397</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>32.875000</td>\n      <td>9.354650</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>2</td>\n      <td>30.000000</td>\n      <td>10.518578</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>3</td>\n      <td>30.600000</td>\n      <td>10.036843</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>4</td>\n      <td>40.666667</td>\n      <td>10.351815</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#cell-fig-danish-interaction .cell execution_count=12}\n``` {.python .cell-code}\nsns.scatterplot(x='age', y='informality', data=df, hue='seniority', palette='viridis')\nplt.ylabel('How informal you can be')\nplt.xlabel('Age')\nplt.legend(title='Seniority', loc='lower right', labels=['Undergrad', 'Postgrad', 'PhD', 'Postdoc', 'Professor'])\nplt.ylim(bottom=0) ;\n```\n\n::: {.cell-output .cell-output-display}\n![Interaction among Danes: How Danes interact is has very little to do with age and seniority, compared to most other contries.](example_files/figure-html/fig-danish-interaction-output-1.svg){#fig-danish-interaction}\n:::\n:::\n\n\nSeems Danish people act very informally unaffected by age and seniority.\n\n\n::: {#cell-23 .cell execution_count=13}\n``` {.python .cell-code}\ninformality_age_cor = df.informality.corr(df.age)\ninformality_age_cor\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```\nnp.float64(0.3974790284326491)\n```\n:::\n:::\n\n\n::: {#cell-24 .cell execution_count=14}\n``` {.python .cell-code}\ninformality_seniority_cor = df.informality.corr(df.seniority)\ninformality_seniority_cor\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\nnp.float64(0.17488501044411855)\n```\n:::\n:::\n\n\n::: {#cell-doc-formality-correlation .cell execution_count=15}\n\n::: {#doc-formality-correlation .cell-output .cell-output-display .cell-output-markdown execution_count=15}\n\n         \nThe correlation between informality and age was 0.397 and the correlation \nbetween informality and seniority was 0.175.\n\n\n:::\n:::\n\n\n::: {#cell-fig-danish-interaction-regressions .cell execution_count=16}\n``` {.python .cell-code}\nsns.lmplot(x='age', y='informality', data=df, hue='seniority', palette='viridis')\nplt.ylabel('How informal you can be')\nplt.xlabel('Age') ;\n```\n\n::: {.cell-output .cell-output-display}\n![Interaction among Danes: Regressions of informality against age for five levels of seniority.](example_files/figure-html/fig-danish-interaction-regressions-output-1.svg){#fig-danish-interaction-regressions}\n:::\n:::\n\n\n\n",
    "supporting": [
      "example_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}